FROM openjdk:11

LABEL maintainer="MUDITMANGAL"
ADD target/pension-disbursement-microservice-0.0.1-SNAPSHOT.jar pension-disbursement-microservice.jar
ENTRYPOINT ["java","-jar","pension-disbursement-microservice.jar"]