version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
    - echo Entered the build phase
    - mvn clean package
  post_build:
     commands:
     - echo Build completed successfully
artifacts:
 files:
    - target/authorization-microservice.jar
 discard-paths: yes
