FROM openjdk:11

LABEL maintainer="MUDITMANGAL"
ADD target/pensioner-detail-microservice-0.0.1-SNAPSHOT.jar pensioner-detail-microservice.jar
ENTRYPOINT ["java","-jar","pensioner-detail-microservice.jar"]